version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: farm_db
      MYSQL_USER: farm_db_user
      MYSQL_PASSWORD: !passw)0rd
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile82
    image: fm_php82_image:latest
    container_name: php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./.docker/php_local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8910:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

volumes:
  mysql_data:
